//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductsLogs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductsLogs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ecommerce.UI.Resources.ProductsLogs", typeof(ProductsLogs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acessou a página de adicionar do produto.
        /// </summary>
        public static string AcessPageCreate {
            get {
                return ResourceManager.GetString("AcessPageCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acessou a página de detalhes do produto.
        /// </summary>
        public static string AcessPageDetails {
            get {
                return ResourceManager.GetString("AcessPageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acessou a página de atualizar do produto.
        /// </summary>
        public static string AcessPageEdit {
            get {
                return ResourceManager.GetString("AcessPageEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acessou a página Index do produto.
        /// </summary>
        public static string AcessPageIndex {
            get {
                return ResourceManager.GetString("AcessPageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acessou a página de remover do produto.
        /// </summary>
        public static string AcessPageRemove {
            get {
                return ResourceManager.GetString("AcessPageRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adicionou um novo produto com o ID:.
        /// </summary>
        public static string ProductCreated {
            get {
                return ResourceManager.GetString("ProductCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to editou o produto com o ID:.
        /// </summary>
        public static string ProductEdited {
            get {
                return ResourceManager.GetString("ProductEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removeu o produto com ID:.
        /// </summary>
        public static string ProductRemoved {
            get {
                return ResourceManager.GetString("ProductRemoved", resourceCulture);
            }
        }
    }
}
